#!/usr/bin/env php

<?php

use App\Controllers\StartController;
use App\Utils\Console;

require 'vendor/autoload.php';

unset($argv[0]);
$argv = array_values($argv);

$console = new Console();

switch ($argv[0]) {
    case "serv":
    case "serve":
    case "start":
        shell_exec("cd public && php -S 127.0.0.1:8000");

        break;
    default:
        $console->print("Command [$argv[0]] Not Found.", "green");

        break;
}